name: Cache Nitter RSS Feed

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' #   Every hour

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch RSS feed
        run: |
          curl -L -A "Mozilla/5.0" https://nitter.poast.org/CUSocialMedia/rss -o feeds/CUSocialMedia.html
          if [ ! -f feeds/CUSocialMedia.xml ]; then
            echo "Failed to fetch RSS feed"
            exit 1
          fi
          
      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add feeds/CUSocialMedia.xml
          git commit -m "Update feed" || echo "No changes"
          git push
